### ISSUE TITLE
Improve docs for github pull workflow

### ISSUE THREAD

**Issue by fwenzel** [mozilla/webdev-bootcamp#17]
Currently, in terms of github workflow we have this:

http://mozweb.readthedocs.org/en/latest/git.html#working-on-projects

I think two things are missing:
1) A slightly more elaborate explanation of these steps and/or weblinks with more information. The goal is to be able to point people (contractors, perhaps) at this and they should know how to get their code reviewed on an ongoing basis.
2) There's no mention of rebasing/squashing commits before sending a pull request or landing it. There are different opinions on this, so we shouldn't go straight for the strictest option, but "squash your list of commits down to a few commits" or so is probably an agreeable opinion across webdev.

**Comment by tofumatt** [comment]
Oh, yeah, seems I closed this ages ago.
